// <auto-generated />
using System;
using ASP_example.data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ASP_example.Migrations
{
    [DbContext(typeof(PostData))]
    partial class PostDataModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ASP_example.Models.Post", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("author")
                        .HasColumnType("int");

                    b.Property<DateTime>("crtate_time")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("edit_time")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("soft_delete")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("Post");
                });
#pragma warning restore 612, 618
        }
    }
}
